# ===== APPLICATION CONFIGURATION =====
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: English Vocab

  # ===== DATABASE CONFIGURATION =====
  datasource:
    url: jdbc:postgresql://localhost:5432/englishvocab
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # ===== JPA/HIBERNATE CONFIGURATION =====
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # ✅ Chỉ validate, không tự động sửa schema
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        jdbc:
          lob:
            '[non_contextual_creation]': true
  
  # ===== FLYWAY MIGRATION =====
  flyway:
    enabled: true
    baseline-on-migrate: true  # Cho phép migrate trên DB có sẵn
    locations: classpath:db/migration

  # ===== REDIS CONFIGURATION =====
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30 minutes (30 * 60 * 1000)
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "englishvocab:"

  # ===== THYMELEAF CONFIGURATION =====
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  # ===== SECURITY CONFIGURATION =====
  # Note: Admin user sẽ được tạo tự động trong database bởi DataInitializer
  # Không cần cấu hình in-memory user nữa
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  # ===== DEV TOOLS =====
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # ===== VALIDATION MESSAGES =====
  messages:
    basename: messages
    encoding: UTF-8

  # ===== FILE UPLOAD CONFIGURATION =====
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

# ===== MEDIA CONFIGURATION =====
media:
  upload:
    dir: uploads  # Thư mục lưu file
  max:
    file:
      size: 10485760  # 10MB
  user:
    quota: 104857600  # 100MB per user

# ===== SERVER CONFIGURATION =====
server:
  port: 8080
  servlet:
    session:
      timeout: 30m

# ===== LOGGING CONFIGURATION =====
logging:
  level:
    '[com.englishvocab]': INFO
    '[org.springframework.security]': WARN
    '[org.springframework.web]': INFO
    '[org.hibernate.SQL]': WARN
    '[org.hibernate.type.descriptor.sql.BasicBinder]': WARN
  file:
    name: logs/englishvocab.log
    '[max-size]': 10MB
    '[max-history]': 30
